### Variáveis de ambiente
@base_url = http://localhost:3333


### POST Settings

###  add username admin
POST {{base_url}}/settings
Content-Type: application/json

{
  "chat": true,
  "username": "admin"
}

### add username marcelo
POST {{base_url}}/settings
Content-Type: application/json

{
  "chat": true,
  "username": "marcelo"
}

### add username maria
POST {{base_url}}/settings
Content-Type: application/json

{
  "chat": true,
  "username": "maria"
}

### add username dani
POST {{base_url}}/settings
Content-Type: application/json

{
  "chat": true,
  "username": "dani"
}