### Variáveis de ambiente
@base_url = http://localhost:3333


### POST Settings

###  add username admin
POST {{base_url}}/users
Content-Type: application/json

{
  "email": "dani@rocketseat.com.br"
}
